name: mtl_perception
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _pytorch_select=0.1=cpu_0
  - _tflow_select=2.3.0=mkl
  - absl-py=0.8.1=py37_0
  - appnope=0.1.0=py37_0
  - astor=0.8.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bzip2=1.0.8=h0b31af3_2
  - c-ares=1.15.0=h1de35cc_1001
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=he1c11cd_1002
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37hb5b8e2f_0
  - colour=0.1.5=py37_0
  - curl=7.71.1=hcb81553_5
  - cycler=0.10.0=py37_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - ffmpeg=4.1.3=h5c2b479_0
  - fontconfig=2.13.1=h6b1039f_1001
  - freetype=2.9.1=hb4e5f40_0
  - gast=0.2.2=py37_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - giflib=5.2.1=h0b31af3_2
  - glib=2.58.3=py37h577aef8_1002
  - gmp=6.2.0=h4a8c4bd_2
  - gnutls=3.6.5=h53004b3_1002
  - google-pasta=0.1.8=py_0
  - graphite2=1.3.13=h2098e52_1000
  - grpcio=1.16.1=py37h044775b_1
  - h5py=2.10.0=nompi_py37h106b333_102
  - harfbuzz=2.4.0=hd8d2a14_3
  - hdf5=1.10.5=nompi_h0cbb7df_1103
  - icu=64.2=h6de7cb9_1
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipython=7.9.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jasper=1.900.1=h636a363_1006
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.1.1=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37h0a44026_0
  - krb5=1.17.1=hddcf347_0
  - lame=3.100=h1de35cc_1001
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libcurl=7.71.1=h9bf37e3_5
  - libcxx=9.0.1=1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libev=4.33=haf1e3a3_1
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=h01d97ff_1005
  - liblapack=3.8.0=14_mkl
  - liblapacke=3.8.0=14_mkl
  - libnghttp2=1.41.0=h8a08a2b_1
  - libopencv=4.2.0=py37_2
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.10.1=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - libssh2=1.9.0=h8a08a2b_5
  - libtiff=4.1.0=hcb84e12_0
  - libwebp=1.0.2=hd3bf737_5
  - libxml2=2.9.10=h53d96d6_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37h54f8f79_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - more-itertools=7.2.0=py37_0
  - nb_conda=2.2.1=py37_0
  - nb_conda_kernels=2.2.2=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - nettle=3.4.1=h3efe00b_1002
  - ninja=1.9.0=py37h04f5b5a_0
  - notebook=6.0.2=py37_0
  - numpy=1.17.3=py37h4174a10_0
  - numpy-base=1.17.3=py37h6575580_0
  - olefile=0.46=py37_0
  - opencv=4.2.0=py37_2
  - openh264=1.8.0=hd9629dc_1000
  - openjpeg=2.3.1=h254dc36_3
  - openssl=1.1.1g=haf1e3a3_1
  - opt_einsum=3.1.0=py_0
  - pandas=0.25.3=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.44=h4a8c4bd_0
  - pdf2image=1.13.1=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.2.1=py37hb68e598_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h01d97ff_1003
  - poppler=0.89.0=h3232a60_0
  - poppler-data=0.4.9=1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - protobuf=3.10.1=py37h0a44026_0
  - ptyprocess=0.6.0=py37_0
  - py-opencv=4.2.0=py37h5ca1d4c_2
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pymongo=3.9.0=py37h0a44026_0
  - pyparsing=2.4.5=py_0
  - pyrsistent=0.15.5=py37h1de35cc_0
  - python=3.7.5=h359304d_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.5.0=py3.7_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.0=py37h0a44026_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.21.3=py37h27c97d8_0
  - scipy=1.1.0=py37h1410ff5_2
  - seaborn=0.9.0=pyh91ea838_1
  - send2trash=1.5.0=py37_0
  - setuptools=41.6.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=ha441bb4_0
  - statsmodels=0.10.1=py37h1d22016_0
  - tensorboard=2.0.0=pyhb230dea_0
  - tensorflow=2.0.0=mkl_py37hda344b4_0
  - tensorflow-base=2.0.0=mkl_py37h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.2=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - torchfile=0.1.0=py_0
  - torchvision=0.6.0=py37_cpu
  - tornado=6.0.3=py37h1de35cc_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h1de35cc_0
  - x264=1!152.20180806=h1de35cc_0
  - xlrd=1.2.0=py37_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
prefix: /Users/biota/opt/anaconda3/envs/tf
